global:
  scrape_interval: 60s
  scrape_timeout: 60s
  evaluation_interval: 60s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
#  <% _.forEach(nodes, (node) => { %>
#  <% _.forEach(vchains, (vchain) => { %>
  - job_name: ${_.kebabCase(node.name)}-${vchain}
    scrape_interval: 60s
    scrape_timeout: 60s
    metrics_path: /vchains/${vchain}/metrics.prometheus
    scheme: http
    static_configs:
      - targets: [ "${node.host}" ]
        labels:
          machine: ${_.kebabCase(node.name)}
          vchain: ${vchain}
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: BlockSync.*
        action: drop
      - source_labels: ['__name__']
        regex: ConsensusAlgo.Benchmark.*
        action: drop
      - source_labels: ['__name__']
        regex: Ethereum.TimestampBlockFinder.*
        action: drop
      - source_labels: ['__name__']
        regex: Gossip.OutgoingConnection.Queue.Usage.*
        action: drop
      - source_labels: ['__name__']
        regex: Gossip.Topic.BenchmarkConsensus.*
        action: drop
      - source_labels: ['__name__']
        regex: Processor.Native.*
        action: drop

#  <% }) %>
#  <% }) %>
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
remote_write:
  - url: ${prometheus.url}
    # Timeout for requests to the remote write endpoint
    remote_timeout: 20s
    basic_auth:
      username: ${prometheus.username}
      password: ${prometheus.password}
    queue_config:
      # Number of samples to buffer per shard before we start dropping them
      capacity: 1000
      # Maximum number of shards, i.e. amount of concurrency
      max_shards: 10
      min_shards: 1
      # Maximum number of samples per send
      max_samples_per_send: 1000
      batch_send_deadline: 10s
      min_backoff: 30ms